"use client";
import React from "react";
import "./styles/main.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "./Components/Navigation/Navigation";
import { motion, useSpring, useScroll } from "framer-motion";
import Menu from "./Components/Menu/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//context
const GlobalContext = React.createContext({
  toggle: false,
  handleToggle: () => {},
});

const GlobalProvider = ({ children }: { children: React.ReactNode }) => {
  const [toggle, setToggle] = React.useState(false);

  const handleToggle = () => {
    setToggle(!toggle);
    console.log("toggle: ", toggle);
  };

  return (
    <GlobalContext.Provider value={{ toggle, handleToggle }}>
      {children}
    </GlobalContext.Provider>
  );
};

export const useGlobalContext = () => {
  return React.useContext(GlobalContext);
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const scrollYProgress = useScroll().scrollYProgress;

  const scaleX = useSpring(scrollYProgress, {
    stiffness: 200,
    damping: 20,
    restDelta: 0.001,
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <motion.div
            className="progress-bar"
            style={{
              scaleX,
            }}
          ></motion.div>
          <Navigation />
          <Menu />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
